import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';

declare let self: ServiceWorkerGlobalScope;

// Take control of all pages immediately
clientsClaim();

// Precache all assets generated by vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache API requests
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new StaleWhileRevalidate({
    cacheName: 'api-cache'
  })
);

// Cache static assets (icons, manifest)
registerRoute(
  ({ request }) => 
    request.destination === 'image' || 
    request.url.includes('manifest.json'),
  new CacheFirst({
    cacheName: 'static-assets'
  })
);

// Handle offline fallback
self.addEventListener('install', () => {
  self.skipWaiting();
});
